export type OrderStatus = "Pending" | "In Progress" | "Completed" | "Delivered";
export type MeasurementUnit = "cm" | "inch";
export type CustomerCategory = "Men" | "Ladies";

export type TailorCustomer = {
  id: string;
  createdAt: string;
  customerName: string;
  customerIdNumber: string;
  phoneNumber: string;
  address: string;
  orderDate: string;
  deliveryDate: string;
  notes: string;
  customerCategory: CustomerCategory;
  outfitType: string;
  measurementType: string;
  measurementUnit: MeasurementUnit;
  qameezLength: string;
  blouseLength: string;
  ghairaBottom: string;
  shoulder: string;
  shoulderDown: string;
  shoulderStrap: string;
  shoulderToApexPoint: string;
  frontChest: string;
  upperChest: string;
  chestWidth: string;
  underChest: string;
  upperBack: string;
  crossBack: string;
  waistWidth: string;
  hip: string;
  sideFittingSeem: string;
  sleeveLength: string;
  armHole: string;
  bicep: string;
  elbow: string;
  forearm: string;
  cuff: string;
  wristCuff: string;
  neckSize: string;
  collarHeight: string;
  collarDesign: string;
  damanWidth: string;
  skirtLength: string;
  choliFrillLength: string;
  waistBelt: string;
  shalwarLength: string;
  shalwarWaist: string;
  crotchRise: string;
  frontRise: string;
  backRise: string;
  rightThigh: string;
  leftThigh: string;
  thigh: string;
  inseamLength: string;
  knees: string;
  calf: string;
  rightCalf: string;
  leftCalf: string;
  ankleBottom: string;
  bottomPoncha: string;
  elastic: boolean;
  zip: boolean;
  sidePocket: boolean;
  frontPocket: boolean;
  fittingStyle: string;
  seamStyle: string;
  neckDesign: string;
  neckDesignValue: string;
  frontStrip: string;
  shoulderStrapDetail: string;
  pocketFlaps: string;
  sleeveStyle: string;
  wristCuffStyle: string;
  cuffDesignValue: string;
  ghairaBottomDetail: string;
  sideChaakSlit: string;
  platesDarts: string;
  buttonDetails: string;
  piping: string;
  dupattaVeil: string;
  shalwarStyle: string;
  pantTrouserStyle: string;
  anklePancha: string;
  fabricType: string;
  suitDesign: string;
  stitchingPrice: string;
  advancePayment: string;
  remainingPayment: string;
  orderStatus: OrderStatus;
};

export type CustomerFormValues = Omit<TailorCustomer, "id" | "createdAt">;

export const emptyCustomerForm: CustomerFormValues = {
  customerName: "",
  customerIdNumber: "",
  phoneNumber: "",
  address: "",
  orderDate: "",
  deliveryDate: "",
  notes: "",
  customerCategory: "Men",
  outfitType: "Normal suit",
  measurementType: "",
  measurementUnit: "inch",
  qameezLength: "",
  blouseLength: "",
  ghairaBottom: "",
  shoulder: "",
  shoulderDown: "",
  shoulderStrap: "",
  shoulderToApexPoint: "",
  frontChest: "",
  upperChest: "",
  chestWidth: "",
  underChest: "",
  upperBack: "",
  crossBack: "",
  waistWidth: "",
  hip: "",
  sideFittingSeem: "",
  sleeveLength: "",
  armHole: "",
  bicep: "",
  elbow: "",
  forearm: "",
  cuff: "",
  wristCuff: "",
  neckSize: "",
  collarHeight: "",
  collarDesign: "",
  damanWidth: "",
  skirtLength: "",
  choliFrillLength: "",
  waistBelt: "",
  shalwarLength: "",
  shalwarWaist: "",
  crotchRise: "",
  frontRise: "",
  backRise: "",
  rightThigh: "",
  leftThigh: "",
  thigh: "",
  inseamLength: "",
  knees: "",
  calf: "",
  rightCalf: "",
  leftCalf: "",
  ankleBottom: "",
  bottomPoncha: "",
  elastic: false,
  zip: false,
  sidePocket: false,
  frontPocket: false,
  fittingStyle: "",
  seamStyle: "",
  neckDesign: "",
  neckDesignValue: "",
  frontStrip: "",
  shoulderStrapDetail: "",
  pocketFlaps: "",
  sleeveStyle: "",
  wristCuffStyle: "",
  cuffDesignValue: "",
  ghairaBottomDetail: "",
  sideChaakSlit: "",
  platesDarts: "",
  buttonDetails: "",
  piping: "",
  dupattaVeil: "",
  shalwarStyle: "",
  pantTrouserStyle: "",
  anklePancha: "",
  fabricType: "",
  suitDesign: "",
  stitchingPrice: "",
  advancePayment: "0",
  remainingPayment: "",
  orderStatus: "Pending"
};
